version = "0.1.6"
titles = [
    "A Economia e a Ética da Propriedade Privada", 
    "Estudos em Economia Política \\& Filosofia"
]
discussions = [["https://en.ancap.ch/t/5", "Ancap Channel"]]
more_infos = [["https://www.google.com", "Website name"]]
tags = ["Some Tag", "Another Tag", "And so on"]
tag_prefix = "https://en.ancap.ch/tags/"

# =============================================================================

content_files = [

    # preface
    ["01_pref2nd_ed.md", ""], 
    ["02_pref1st_ed.md", ""], 
    
    # part 1
    ["03_p01.md", ""],

    # chapter 1
    ["03_p01_ch01_01.md", ""],
    ["03_p01_ch01_02.md", ""], 
    ["03_p01_ch01_03.md", ""]

    # chapter 2
    # ["03_p01_ch02_01.md", ""], 
    # ["03_p01_ch02_02.md", ""], 
    # ["03_p01_ch02_03.md", ""], 
    # ["03_p01_ch02_04.md", ""], 
    # ["03_p01_ch02_05.md", ""], 

    # # chapter 3
    # ["03_p01_ch03_01.md", ""], 
    # ["03_p01_ch03_02.md", ""], 
    # ["03_p01_ch03_03.md", ""], 
    # ["03_p01_ch03_04.md", ""], 
    # ["03_p01_ch03_05.md", ""], 

    # # chapter 4
    # ["03_p01_ch04_01.md", ""], 
    # ["03_p01_ch04_02.md", ""], 

    # # chapter 5
    # ["03_p01_ch05_01.md", ""], 
    # ["03_p01_ch05_02.md", ""], 
    # ["03_p01_ch05_03.md", ""], 
    # ["03_p01_ch05_04.md", ""], 

    # # chapter 6
    # ["03_p01_ch06_01.md", ""], 
    # ["03_p01_ch06_02.md", ""], 
    # ["03_p01_ch06_03.md", ""], 

    # # chapter 7
    # ["03_p01_ch07_01.md", ""], 
    # ["03_p01_ch07_02.md", ""], 
    # ["03_p01_ch07_03.md", ""], 
    # ["03_p01_ch07_04.md", ""], 
    # ["03_p01_ch07_05.md", ""], 
    # ["03_p01_ch07_06.md", ""], 

    # # chapter 8
    # ["03_p01_ch08.md", ""], 

    # # part 2
    # ["03_p02.md", ""], 

    # # chapter 9
    # ["03_p02_ch09.md", ""], 
    # ["03_p02_ch09_01.md", ""], 
    # ["03_p02_ch09_02.md", ""], 
    # ["03_p02_ch09_03_01.md", ""], 
    # ["03_p02_ch09_03_02.md", ""], 
    # ["03_p02_ch09_04.md", ""],

    # # chapter 10
    # ["03_p02_ch10.md", ""], 

    # # chapter 11
    # ["03_p02_ch11.md", ""], 
    # ["03_p02_ch11_1.md", ""], 
    # ["03_p02_ch11_2.md", ""], 
    # ["03_p02_ch11_3.md", ""], 

    # # chapter 12
    # ["03_p02_ch12.md", ""], 

    # # chapter 13
    # ["03_p02_ch13.md", ""], 

    # # chapter 14
    # ["03_p02_ch14.md", ""], 
    # ["03_p02_ch14_1.md", ""], 
    # ["03_p02_ch14_2.md", ""], 
    # ["03_p02_ch14_3.md", ""],

    # # chapter 15
    # ['04_apx.md', ""],
    # ['04_apx_01.md', ""],
    # ['04_apx_02.md', ""],
    # ['04_apx_03.md', ""],
    # ['04_apx_04.md', ""]

]

[translation]
language = "pt-BR"
other_languages = ["en"]
is_translation = true
this_project_url = "https://github.com/ancap-ch/from-en/tree/utopian/pt-BR/Economics and Ethics of Private Property Studies in Political Economy and Philosophy"
fetch_translators = true
fetch_reviwers = true
fetch_progress = true


[[resources]]
rule = "front_cover"
content = "Pasture_and_Rail_Fence.jpg"
description = "A pasture overlooks rolling hills in Switzerland. By Joseph Clemens (Klemenz) Kaufmann (7.2.1867 - 21.11.1926)"
websites = ["https://commons.wikimedia.org/wiki/File:Pasture_and_Rail_Fence.jpg"]
persons = ["template_person"]

# =============================================================================

# a4 book print
[[targets]]
name = "book"
size = "a4paper"
orientation = "portrait"
font_size = "17pt"
reader = "print"
engine = "latex"
titles = ["A Economia \\,e\\, a Ética", "da Propriedade Privada", "Estudos em Economia Política", "\\qquad\\qquad\\qquad\\qquad\\quad\\,\\,\\,\\& Filosofia"]
reset_footer_active = true
reset_footer_depth = 2
clear_page_active = false
clear_page_depth = 0
has_parts = true
frontmatter_depth = 2
toc_depth = 0
mini_toc_active = true
mini_toc_depth = 2
mini_toc_sec_active = true
mini_toc_sec_depth = 2

[[targets.covers]]
cover_file = "Pasture_and_Rail_Fence.jpg"
cover_dimensions = [0, 0, 1198, 1695] # 210x297 * ~5.70

# -------------------------------------------------

# phone portrait
[[targets]]
name = "article"
size = "hd720"
orientation = "portrait"
font_size = "25pt"
reader = "digital"
engine = "latex"
titles = ["A Economia \\,\\,e\\,\\, a Ética", "da Propriedade Privada", "Estudos em Economia Política", "\\qquad\\qquad\\qquad\\qquad\\quad\\,\\,\\,\\& Filosofia"]
reset_footer_active = true
reset_footer_depth = 2
clear_page_active = true
clear_page_depth = 2
has_parts = true
frontmatter_depth = 2
toc_depth = 0
mini_toc_active = true
mini_toc_depth = 2
mini_toc_sec_active = true
mini_toc_sec_depth = 2

[[targets.covers]]
cover_file = "Pasture_and_Rail_Fence.jpg"
cover_dimensions = [0, 0, 951, 1691] # 9x16 * ~105.6

# -------------------------------------------------

# phone landscape
[[targets]]
name = "article"
size = "hd720"
orientation = "landscape"
font_size = "36pt"
reader = "digital"
engine = "latex"
titles = ["A Economia \\,\\,e\\,\\, a Ética", "da Propriedade Privada", "Estudos em Economia Política", "\\qquad\\qquad\\qquad\\qquad\\quad\\,\\,\\,\\& Filosofia"]
reset_footer_active = true
reset_footer_depth = 2
clear_page_active = true
clear_page_depth = 2
has_parts = true
frontmatter_depth = 2
toc_depth = 0
mini_toc_active = true
mini_toc_depth = 2
mini_toc_sec_active = true
mini_toc_sec_depth = 2

[[targets.covers]]
cover_file = "Pasture_and_Rail_Fence.jpg"
cover_dimensions = [0, 334, 2419, 1361] # 16x9 * ~151

# -------------------------------------------------

# tablet portrait
[[targets]]
name = "article"
size = "xga"
orientation = "portrait"
font_size = "20pt"
reader = "digital"
engine = "latex"
titles = ["A Economia \\,\\,e\\,\\, a Ética", "da Propriedade Privada", "Estudos em Economia Política", "\\qquad\\qquad\\qquad\\qquad\\quad\\,\\,\\,\\& Filosofia"]
reset_footer_active = true
reset_footer_depth = 2
clear_page_active = true
clear_page_depth = 2
has_parts = true
frontmatter_depth = 2
toc_depth = 0
mini_toc_active = true
mini_toc_depth = 2
mini_toc_sec_active = true
mini_toc_sec_depth = 2

[[targets.covers]]
cover_file = "Pasture_and_Rail_Fence.jpg"
cover_dimensions = [0, 0, 1268, 1691] # 3x4 * ~422

# -------------------------------------------------


# tablet landscape
[[targets]]
name = "article"
size = "xga"
orientation = "landscape"
font_size = "25pt"
reader = "digital"
engine = "latex"
titles = ["A Economia \\,\\,e\\,\\, a Ética", "da Propriedade Privada", "Estudos em Economia Política", "\\qquad\\qquad\\qquad\\qquad\\quad\\,\\,\\,\\& Filosofia"]
reset_footer_active = true
reset_footer_depth = 2
clear_page_active = true
clear_page_depth = 2
has_parts = true
frontmatter_depth = 2
toc_depth = 0
mini_toc_active = true
mini_toc_depth = 2
mini_toc_sec_active = true
mini_toc_sec_depth = 2

[[targets.covers]]
cover_file = "Pasture_and_Rail_Fence.jpg"
cover_dimensions = [0, 0, 2256, 1692] # 4x3 * 564

# =============================================================================

[[persons]]
identifier = "Hans-Hermann Hoppe"
rule = "author"

[[persons]]
identifier = "template_person"
rule = "collaborator"

[[persons]]
identifier = "template_person"
rule = "thanked"

[[persons]]
identifier = "template_person"
rule = "translator"

[[persons]]
identifier = "template_person"
rule = "reviwer"

[[persons]]
identifier = "template_person"
rule = "cover_artist"

[[persons]]
identifier = "template_person"
rule = "artist"

