version = "0.1.4"
titles = ["A Catedral", "\\& o Bazar"]
discussions = [["https://en.ancap.ch/t/5", "Ancap Channel"]]
more_infos = [["https://www.google.com", "Website name"]]
tags = ["Some Tag", "Another Tag", "And so on"]
tag_prefix = "https://en.ancap.ch/tags/"

content_files = [["content.md", ""]]

[translation]
language = "pt-BR"
is_translation = true
this_project_url = "https://github.com/farribeiro/catb-ptbr"
fetch_translators = true
fetch_reviwers = true
fetch_progress = true


[[resources]]
rule = "front_cover"
content = "test.jpg"
description = "This is an original Artwork, handmade and with a Certificate Of Authenticity. Painted by Milen Tod."
websites = ["http://milen.com/product/abstract-city-abstract-cityscape-painting/"]
persons = ["template_person"]

[[targets]]
name = "book"
size = "a4paper"
reader = "print"
reset_footer_active = false
reset_footer_depth = 2
clear_page_active = false
clear_page_depth = 2
has_parts = false
frontmatter_depth = 1
toc_depth = 0
mini_toc_active = true
mini_toc_depth = 2
mini_toc_sec_active = true
mini_toc_sec_depth = 2

[[targets.covers]]
cover_file = "test.jpg"
cover_dimensions = [0, 0, 706, 888]


[[persons]]
identifier = "Eric S. Raymond"
rule = "author"

[[persons]]
identifier = "template_person"
rule = "collaborator"

[[persons]]
identifier = "template_person"
rule = "thanked"

[[persons]]
identifier = "template_person"
rule = "translator"

[[persons]]
identifier = "template_person"
rule = "reviwer"

[[persons]]
identifier = "template_person"
rule = "cover_artist"

[[persons]]
identifier = "template_person"
rule = "artist"

